## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('mq-codel',
                                 ['point-to-point', 'applications', 'internet'])
    obj.source = 'mq-codel.cc'
    
    obj = bld.create_ns3_program('codel-dctcp',
                                 ['point-to-point', 'applications', 'internet'])
    obj.source = 'codel-dctcp.cc'
